FIREBASE_API_KEY = "AIzaSyCffq3eNYuT3UELa1Z3UU1kbsE-GP8_Iow"
FIREBASE_AUTH_DOMAIN = "ballslogistics.firebaseapp.com"
FIREBASE_DATABASE_URL = "https://ballslogistics-default-rtdb.firebaseio.com"
FIREBASE_PROJECT_ID = "ballslogistics"

# IMPORTANT: storageBucket should be "<project-id>.appspot.com"
# (The console line you pasted shows firebasestorage.app, which is a CDN domain,
# not the bucket name. Pyrebase expects the bucket name.)
FIREBASE_STORAGE_BUCKET = "ballslogistics.appspot.com"

FIREBASE_MESSAGING_SENDER_ID = "692014599824"
FIREBASE_APP_ID = "1:692014599824:web:62b1113d7bc14b1bd11215"

# your cookie key
cookie_password = "a-very-long-random-string"
